apiVersion: apps/v1
kind: Deployment
metadata:
  name: ham-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: datacollector
        env:
        - name: APP_STAGE
          value: "production"
