---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ham-deployment
  labels:
    app: ham
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ham
  template:
    metadata:
      labels:
        app: ham 
    spec:
      containers:
      - name: datacollector
        image: local-registry.registry.svc.cluster.local:5000/datacollector
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      - name: datacollector-producer
        image: local-registry.registry.svc.cluster.local:5000/datacollectorproducer
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8083
        env:
          - name: KAFKA_BROKERS
            value: "kafka.kafka.svc.cluster.local:9092"
          - name: KAFKA_TOPIC
            value: "remote-requests"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/nginx_status"
        ports:
        - containerPort: 9113
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"

