---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ham-deployment
  labels:
    app: ham
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ham
  template:
    metadata:
      labels:
        app: ham 
    spec:
      containers:
      - name: executor
        image: local-registry.registry.svc.cluster.local:5000/executor
        ports:
        - containerPort: 8081
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/nginx_status"
        ports:
        - containerPort: 9113


