apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    app: ham
spec:
  type: NodePort
  selector:
    app: ham
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30083
