resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b697747b309d93c46397e25d1bed773794df71293ad9f4fbd365a0fc902cde2a
  name: executor
  newName: local-registry.registry.svc.cluster.local:5000/executor
- digest: sha256:4ccec648674b22ef24d6f3916dc7266022ee01d023b0e606a7b0bb58b2ad5660
  name: nginx
  newName: local-registry.registry.svc.cluster.local:5000/executor
  newTag: latest
